### ISSUE TITLE
Better Babies invisible mobs

### ISSUE THREAD

**Issue by VinceKezel** [GenMode/Minecraft#2]
When I spawn a Better Baby in, it seems to create a regular mob with invisibility and an invisible armor stand as well. The spectators can see this.

When picking up a Better Baby with Carry On mod, the baby mob dies instantly, and the invisible mob stays.

Also, putting the command `/function settings:better_babies` shows `Unknown function settings:better_babies`

_Minecraft 1.20.1
Fabric Loader 0.14.22  /  Fabric Api 0.90.0
Better Babies 0.6_

**Comment by GenMode** [comment]
the settings should be `/function gen_baby:settings` in that update

The invisible mob is because it's a datapack and is working as intended as the armor stand is the model and the mob is the actual mob

As for the Carry On mod compatibility does the mob regain its model when its placed down again or is it still invisible? And you say the model dies does it just disappear or does it play the death animation?

**Comment by VinceKezel** [comment]
https://github.com/GenMode/Minecraft/assets/49579475/aa0efc9a-cf03-403f-97b3-349cca59341e

**Comment by GenMode** [comment]
Ok I will get on this thank you for notifying me

at the very least I'll work on it recovering its model when placed back down

**Comment by Pinkietron** [comment]
This issue is still happening as of today on fabric except the baby is a clay ball with no visible hitbox

**Comment by GenMode** [comment]
Sorry for the wait I know it's been awhile, but I can assure you the next update of Better Babies will be compatible with the Carrry On mod. Thank you for your patience
